SPRITE_SCALING = 0.4
SPRITE_SIZE = int(128 * SPRITE_SCALING)

CAR_WIDTH = int(256 * SPRITE_SCALING)

MAP_COL = 17  # Odd number only
MAP_ROW = 15

WINDOW_WIDTH = MAP_COL * SPRITE_SIZE
WINDOW_HEIGHT = MAP_ROW * SPRITE_SIZE